workflows:
  omnisms-prod:
    name: Omnisms Production
    instance_type: linux_x2 # RAPIDE + GRATUIT
    max_build_duration: 30
    
    scripts:
      - name: Set Flutter
        script: flutter upgrade --force
        
      - name: Clean & deps
        script: |
          flutter clean
          flutter pub get
          
      - name: Keystore
        script: |
          keytool -genkey -v -keystore android/app/release-key.jks \
            -storepass omnisms2026 -keypass omnisms2026 \
            -alias omnisms-key -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Omnisms"
            
      - name: APK test
        script: flutter build apk --release
        
      - name: AAB PlayStore
        script: flutter build appbundle --release
        
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/flutter-apk/*.apk
