workflows:
  omnisms-prod:
    name: Omnisms Production
    instance_type: mac_mini_m1  # ✅ GRATUIT 500min/mois
    max_build_duration: 45
    
    scripts:
      - name: Get Flutter
        script: flutter upgrade
        
      - name: Clean & deps
        script: |
          flutter clean
          flutter pub get
          
      - name: Create key.properties
        script: |
          cat > android/key.properties << EOF
          storePassword=omnisms2026
          keyPassword=omnisms2026
          keyAlias=omnisms-key
          storeFile=release-key.jks
          EOF
      
      - name: Generate keystore
        script: |
          keytool -genkey -v -keystore android/app/release-key.jks \
            -storepass omnisms2026 -keypass omnisms2026 \
            -alias omnisms-key -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Omnisms"
            
      - name: Build APK
        script: flutter build apk --release
        
      - name: Build AAB
        script: flutter build appbundle --release
        
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/flutter-apk/*.apk
